apiVersion: v1
kind: Service
metadata:
 name: i-diveshsrivastava-master-service
 namespace: kubernetes-cluster-diveshsrivastava
spec:
 type: LoadBalancer
 ports:
 - targetPort: 5000
   port: 80
   protocol: TCP
 selector:
  app: i-diveshsrivastava-master
