apiVersion: v1
kind: Service
metadata:
 name: i-diveshsrivastava-develop-service
 namespace: kubernetes-cluster-diveshsrivastava
spec:
 type: LoadBalancer
 ports:
 - targetPort: 5050
   port: 8050
   protocol: TCP
 selector:
  app: i-diveshsrivastava-develop
